In [1]:
import pandas as pd
import dotenv
config = dotenv.dotenv_values("./.env")
import json
from dateutil import parser
import TweetExtraction as te

In [2]:
with open('./data/id_chunk4.jsonl') as f:

    lens = 0
    ctr = 0

    for line in f:
        
        try:
            tweet = json.loads(line)
            status = tweet['retweeted_status']
        except KeyError as e:
            display(tweet)
            break
        except Exception as e:
            print(e)
            continue

{'created_at': 'Thu Jun 28 23:05:16 +0000 2018',
 'id': 1012472026672574500,
 'id_str': '1012472026672574464',
 'full_text': 'Here are 4 ways we can adapt to the growing danger of climate change https://t.co/S8eiZDHgWh #environment https://t.co/KKjPABOyqZ',
 'truncated': False,
 'display_text_range': [0, 129],
 'entities': {'hashtags': [{'text': 'environment', 'indices': [93, 105]}],
  'symbols': [],
  'user_mentions': [],
  'urls': [{'url': 'https://t.co/S8eiZDHgWh',
    'expanded_url': 'https://wef.ch/2JYZzpm',
    'display_url': 'wef.ch/2JYZzpm',
    'indices': [69, 92]}],
  'media': [{'id': 1012470726891274200,
    'id_str': '1012470726891274240',
    'indices': [106, 129],
    'media_url': 'http://pbs.twimg.com/media/Dg0EwwXWAAAV9Jd.jpg',
    'media_url_https': 'https://pbs.twimg.com/media/Dg0EwwXWAAAV9Jd.jpg',
    'url': 'https://t.co/KKjPABOyqZ',
    'display_url': 'pic.twitter.com/KKjPABOyqZ',
    'expanded_url': 'https://twitter.com/wef/status/1012470730506809346/photo/1',
    'type': 'photo',
    'sizes': {'medium': {'w': 1200, 'h': 682, 'resize': 'fit'},
     'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
     'small': {'w': 680, 'h': 386, 'resize': 'fit'},
     'large': {'w': 1596, 'h': 907, 'resize': 'fit'}},
    'source_status_id': 1012470730506809300,
    'source_status_id_str': '1012470730506809346',
    'source_user_id': 5120691,
    'source_user_id_str': '5120691'}]},
 'extended_entities': {'media': [{'id': 1012470726891274200,
    'id_str': '1012470726891274240',
    'indices': [106, 129],
    'media_url': 'http://pbs.twimg.com/media/Dg0EwwXWAAAV9Jd.jpg',
    'media_url_https': 'https://pbs.twimg.com/media/Dg0EwwXWAAAV9Jd.jpg',
    'url': 'https://t.co/KKjPABOyqZ',
    'display_url': 'pic.twitter.com/KKjPABOyqZ',
    'expanded_url': 'https://twitter.com/wef/status/1012470730506809346/photo/1',
    'type': 'photo',
    'sizes': {'medium': {'w': 1200, 'h': 682, 'resize': 'fit'},
     'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
     'small': {'w': 680, 'h': 386, 'resize': 'fit'},
     'large': {'w': 1596, 'h': 907, 'resize': 'fit'}},
    'source_status_id': 1012470730506809300,
    'source_status_id_str': '1012470730506809346',
    'source_user_id': 5120691,
    'source_user_id_str': '5120691'}]},
 'source': '<a href="https://ifttt.com" rel="nofollow">IFTTT</a>',
 'in_reply_to_status_id': None,
 'in_reply_to_status_id_str': None,
 'in_reply_to_user_id': None,
 'in_reply_to_user_id_str': None,
 'in_reply_to_screen_name': None,
 'user': {'id': 44132435,
  'id_str': '44132435',
  'name': 'Random Thoughts Abal',
  'screen_name': 'auliakbar',
  'location': 'Singapore',
  'description': '',
  'url': None,
  'entities': {'description': {'urls': []}},
  'protected': False,
  'followers_count': 248,
  'friends_count': 206,
  'listed_count': 71,
  'created_at': 'Tue Jun 02 14:56:06 +0000 2009',
  'favourites_count': 168,
  'utc_offset': None,
  'time_zone': None,
  'geo_enabled': False,
  'verified': False,
  'statuses_count': 89793,
  'lang': None,
  'contributors_enabled': False,
  'is_translator': False,
  'is_translation_enabled': False,
  'profile_background_color': '000000',
  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme2/bg.gif',
  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme2/bg.gif',
  'profile_background_tile': False,
  'profile_image_url': 'http://pbs.twimg.com/profile_images/1453743618066292746/CZ5jjy5L_normal.jpg',
  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1453743618066292746/CZ5jjy5L_normal.jpg',
  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/44132435/1635434463',
  'profile_link_color': '3B94D9',
  'profile_sidebar_border_color': '000000',
  'profile_sidebar_fill_color': '000000',
  'profile_text_color': '000000',
  'profile_use_background_image': False,
  'has_extended_profile': False,
  'default_profile': False,
  'default_profile_image': False,
  'following': False,
  'follow_request_sent': False,
  'notifications': False,
  'translator_type': 'none',
  'withheld_in_countries': []},
 'geo': None,
 'coordinates': None,
 'place': None,
 'contributors': None,
 'is_quote_status': False,
 'retweet_count': 0,
 'favorite_count': 0,
 'favorited': False,
 'retweeted': False,
 'possibly_sensitive': False,
 'lang': 'en'}

## Collecting Retweet Network

In [2]:

chunk_files = [
    './data/id_chunk0.jsonl', 
    # './data/id_chunk1.jsonl', 
    # './data/id_chunk2.jsonl', 
    # './data/id_chunk3.jsonl', 
    # './data/id_chunk4.jsonl',
    # './data/id_chunk_comp0.jsonl',
    # './data/id_chunk_comp1.jsonl',
    # './data/id_chunk_comp2.jsonl',
    # './data/id_chunk_comp3.jsonl',
    # './data/id_chunk_comp4.jsonl',
    # './data/id_chunk_comp5.jsonl',
    # './data/id_chunk_comp6.jsonl',
    # './data/id_chunk_comp7.jsonl',
    # './data/id_chunk_comp8.jsonl',
    # './data/id_chunk_comp9.jsonl'
]

retweet_list = []
for chunk in chunk_files:
    retweet_list = retweet_list + te.get_hydrated_retweets(chunk)
retweet_df = pd.DataFrame(retweet_list)

In [3]:
print(f"There are {len(retweet_df)} observations in the retweet sample")

There are 364838 observations in the retweet sample

In [4]:
display(retweet_df.head(5))

,id,text,influencer,author_id,author_name,author_followers,infl_followers,infl_verified,infl_total,infl_begin
0,939997782416375809,RT @Salon: Bringing women together to fight cl...,Salon,87937530,DraIsabel,8547,947935,True,247007,2008-10-24 20:13:31+00:00
1,1054397681781628929,RT @UNmigration: How #climatechange affects mi...,UNmigration,781209744715513900,Speak535,1029,210890,True,35842,2009-10-27 01:32:17+00:00
2,1012588369300209668,RT @GreenAwakening: global warming—if emission...,GreenAwakening,562243642,sjandrews76,4316,16921,False,21386,2009-05-03 20:08:41+00:00
3,1129733520681787392,RT @AOC: To the GOP extremists trying to invok...,AOC,23590046,TeriLOC,3208,13500648,True,14384,2010-04-28 22:38:40+00:00
4,1054103861173067777,RT @amxrino: The UN confirmed that we only hav...,amxrino,717417065989148700,incognit0m0de,799,876,False,7635,2014-02-17 21:27:50+00:00

In [6]:
len(retweet_df.drop_duplicates())

5437129

In [5]:
retweet_df.drop_duplicates().to_pickle('./data/retweetsCumulativeChunk.pkl')

### Collecting Echoer Data

In [ ]:

chunk_files = [
    './data/id_chunk0.jsonl', 
    './data/id_chunk1.jsonl', 
    './data/id_chunk2.jsonl', 
    './data/id_chunk3.jsonl', 
    './data/id_chunk4.jsonl',
    './data/id_chunk_comp0.jsonl',
    './data/id_chunk_comp1.jsonl',
    './data/id_chunk_comp2.jsonl',
    './data/id_chunk_comp3.jsonl',
    './data/id_chunk_comp4.jsonl',
    './data/id_chunk_comp5.jsonl',
    './data/id_chunk_comp6.jsonl',
    './data/id_chunk_comp7.jsonl',
    './data/id_chunk_comp8.jsonl',
    './data/id_chunk_comp9.jsonl'
]

tweet_list = []
for chunk in chunk_files:
    tweet_list = tweet_list + te.get_hydrated_echoer_tweets(chunk, './data/echoer.json')
tweet_df = pd.DataFrame(tweet_list)

In [ ]:
print(len(tweet_df))
tweet_df.head()

75615

,id,text,echoer_id,echoer_name,echoer_followers,echoer_verified,echoer_total,echoer_begin
0,1014010874061783041,Here come the funds! #Greece could be a step c...,295713773,TRF,45082,True,65892,2011-05-09 14:56:22+00:00
1,965300214591471616,Flooding is one impact of tropical cyclones th...,142864417,ClimateSignals,7336,True,8200,2010-05-11 23:57:22+00:00
2,746244653930905600,What does climate change mean for The County? ...,2915468150,climate_u,123,False,54448,2014-12-01 09:36:02+00:00
3,947017758939721729,Why is the Gulf Stream About to Halt? Find out...,4008390124,AroundOMedia,34433,False,459516,2015-10-21 09:05:07+00:00
4,971149596343848961,"GOP is losing us over climate change, say Harv...",798890670,C_Coolidge,12435,False,573555,2012-09-02 19:26:38+00:00

In [ ]:
print(f"There are {len(tweet_df)} observations in the tweet sample")

There are 75615 observations in the retweet sample

In [ ]:
tweet_df.drop_duplicates().to_pickle('./data/echoerTweets.pkl')

In [8]:
# BEARER = config['TWITTER_BEARER_TOKEN']
# headers = {"Authorization": f"Bearer {BEARER}"}
# params = { 
#     'tweet.fields':'id,text,author_id,conversation_id,referenced_tweets',
#     'user.fields' : 'name,username'
#  }

# ids = [str(id) for id in list(tweets_df['id'])]
# tweetIds = [",".join(ids[i:i + 100]) for i in range(0, len(ids), 100)]

# def is_cnx_active(timeout):
#     try:
#         urlopen('http://www.google.com', timeout=timeout)
#         return True
#     except: 
#         return False

# results = []
# ctr = 0
# for id_chunks in tweetIds:
#     ctr = ctr + 1
#     if ctr % 300 == 0: tm.sleep(900)
#     print(ctr, end='\r')
#     params['ids'] = id_chunks

#     try: 
#         res = req.get("https://api.twitter.com/2/tweets", params=params, headers=headers)
#     except ConnectionError:
#         while True:
#             if is_cnx_active(5) is True:
#                 # Do somthing
#                 print("The internet connection is active")
#                 break
#             else:
#                 print("The internet connection is inactive")
#                 pass

#     temp = [ payload for payload in res.json()['data'] ]
#     results = results + temp

# retweeted = []
# for tweet in results:
#     try:
#         temp = {}
#         for ref in tweet['referenced_tweets']:
#             if ref['type'] == 'retweeted':
#                 temp['id'] = tweet['id']
#                 temp['author_id'] = tweet['author_id']
#                 temp['retweeted'] = ref['id']
#                 temp['text'] = tweet['text']
#                 retweeted.append(temp)
#     except: continue

# retweet_df = pd.DataFrame(retweeted)